" Vim Configuration File
" Author: Nav Ganti (http://www.github.com/navganti/dotfiles/vim)
" Note: Built off of Christopher Choi's Vim configuration
" (http://www.github.com/chutsu/dotfiles/vim)

" Vundle setup
function! Vundle()
    	set nocompatible              " be iMproved, required
	filetype off       

	" set the runtime path to include Vundle and initialize
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()
	" alternatively, pass a path where Vundle should install plugins
	" call vundle#begin('~/some/path/here')
	
	" let Vundle manage Vundle, required
	Plugin 'gmarik/Vundle.vim'

	" Plugins
	Plugin 'tpope/vim-fugitive'	" Git wrapper for vim
	Plugin 'tpope/vim-surround'	" Enhancement for surroundings: parentheses, brackets, etc.
	Plugin 'tomtom/tcomment_vim'	" Sensible comment toggling
	Plugin 'scrooloose/nerdtree'	" Tree explorer plugin for vim	
	Plugin 'Xuyuanp/nerdtree-git-plugin'	" Git status indicator for each file in nerdtree


	" All of your Plugins must be added before the following line
	call vundle#end()		" required
	filetype plugin indent on	" required
	" To ignore plugin indent changes, instead use:
	" filetype plugin on
	" Brief help
	" :PluginList       - lists configured plugins
	" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
	" :PluginSearch foo - searches for foo; append `!` to refresh local cache
	" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
	
	" see :h vundle for more details or wiki for FAQ
	" Put your non-Plugin stuff after this line
endfunction

" Start NERDTree with every Vim instance
function! StartNERDTree()
	autocmd VimEnter * NERDTree
endfunction

" Paramters for appearance
function! EditorAppearance()
	syntax on
	set number
endfunction



" MAIN
call Vundle()
call StartNERDTree()
call EditorAppearance()
