" Vim Configuration File
" Author: Nav Ganti (http://www.github.com/navganti/dotfiles/vim)

" Vundle setup
function! Vundle()
    	set nocompatible              " be iMproved, required
	filetype off       

	" set the runtime path to include Vundle and initialize
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()
	" alternatively, pass a path where Vundle should install plugins
	" call vundle#begin('~/some/path/here')
	
	" let Vundle manage Vundle, required
	Plugin 'gmarik/Vundle.vim'

	" Plugins
	Plugin 'tpope/vim-fugitive'	" Git wrapper for vim
	Plugin 'tpope/vim-surround'	" Enhancement for surroundings: parentheses, brackets, etc.	
	Plugin 'vim-airline/vim-airline'  " Status/tabline for vim
	Plugin 'vim-airline/vim-airline-themes'  "Airline themes
	Plugin 'NLKNguyen/papercolor-theme'  "Theme
	Plugin 'octol/vim-cpp-enhanced-highlight'  "C++ Syntax
	Plugin 'godlygeek/tabular'
	Plugin 'plasticboy/vim-markdown'
	Plugin 'scrooloose/nerdtree'

	" All of your Plugins must be added before the following line
	call vundle#end()		" required
	filetype plugin indent on	" required
	" To ignore plugin indent changes, instead use:
	" filetype plugin on
	" Brief help
	" :PluginList       - lists configured plugins
	" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
	" :PluginSearch foo - searches for foo; append `!` to refresh local cache
	" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
	
	" see :h vundle for more details or wiki for FAQ
	" Put your non-Plugin stuff after this line
endfunction

" Paramters for appearance
function! EditorAppearance()
	syntax on
	set number
	set laststatus=2
	set background=dark
	colorscheme PaperColor
endfunction

function! EscapeCommonOperationTypos()
	cmap Wq wq
	cmap WQ wq
	cmap Q q
	map <C-n> <TAB>
endfunction


" MAIN
call Vundle()
call EditorAppearance()
call EscapeCommonOperationTypos()
